### ISSUE TITLE
Cannot find module 'mime/lite' error after 4.0.1 upgrade

### ISSUE THREAD

**Issue by sinedied** [broofa/mime#302]
After upgrading to 4.0.1, neither using `import mime from 'mime/lite'` nor `import mime2 from 'mime/lite.js'` works in my TypeScript project.

This is the error I'm getting:
```
error.ts:1:18 - error TS2307: Cannot find module 'mime/lite' or its corresponding type declarations.
```
My project use ES modules, and my TS config includes the following settings:
```
    "module": "esnext",
    "moduleResolution": "node",
```

MRE: https://stackblitz.com/~/github.com/sinedied/mime-issue

Run `npm run build` in the terminal.

Thanks for your help.

**Comment by broofa** [comment]
Change `moduleResolution` to `node16` or `nodenext`.    'Should fix the problem.

You may also want to change `module` to `nodenext` as well.  Up to you... This is discussed in the [ESM Module FAQ](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#can-i-import-esm-packages-in-my-typescript-project) (linked in README).

>  `import mime2 from 'mime/lite.js'`

This is not expected to work.  
The export name is "mime/lite".  No '.js' extension.
